welcome = """
░██╗░░░░░░░██╗███████╗██╗░░░░░░█████╗░░█████╗░███╗░░░███╗███████╗  ████████╗░█████╗░
░██║░░██╗░░██║██╔════╝██║░░░░░██╔══██╗██╔══██╗████╗░████║██╔════╝  ╚══██╔══╝██╔══██╗
░╚██╗████╗██╔╝█████╗░░██║░░░░░██║░░╚═╝██║░░██║██╔████╔██║█████╗░░  ░░░██║░░░██║░░██║
░░████╔═████║░██╔══╝░░██║░░░░░██║░░██╗██║░░██║██║╚██╔╝██║██╔══╝░░  ░░░██║░░░██║░░██║
░░╚██╔╝░╚██╔╝░███████╗███████╗╚█████╔╝╚█████╔╝██║░╚═╝░██║███████╗  ░░░██║░░░╚█████╔╝
░░░╚═╝░░░╚═╝░░╚══════╝╚══════╝░╚════╝░░╚════╝░╚═╝░░░░░╚═╝╚══════╝  ░░░╚═╝░░░░╚════╝░
"""

logo = """
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                     dddddddd                                                                                                                                                                                        
PPPPPPPPPPPPPPPPP                          PPPPPPPPPPPPPPPPP                                                                                                                                         d::::::d             GGGGGGGGGGGGG                                                                                                      tttt                                                !!! 
P::::::::::::::::P                         P::::::::::::::::P                                                                                                                                        d::::::d          GGG::::::::::::G                                                                                                   ttt:::t                                               !!:!!
P::::::PPPPPP:::::P                        P::::::PPPPPP:::::P                                                                                                                                       d::::::d        GG:::::::::::::::G                                                                                                   t:::::t                                               !:::!
PP:::::P     P:::::P                       PP:::::P     P:::::P                                                                                                                                      d:::::d        G:::::GGGGGGGG::::G                                                                                                   t:::::t                                               !:::!
  P::::P     P:::::Pyyyyyyy           yyyyyyyP::::P     P:::::Paaaaaaaaaaaaa      ssssssssss       sssssssssswwwwwww           wwwww           wwwwwww ooooooooooo   rrrrr   rrrrrrrrr       ddddddddd:::::d       G:::::G       GGGGGG    eeeeeeeeeeee    nnnn  nnnnnnnn        eeeeeeeeeeee    rrrrr   rrrrrrrrr   aaaaaaaaaaaaa  ttttttt:::::ttttttt       ooooooooooo   rrrrr   rrrrrrrrr   !:::!
  P::::P     P:::::P y:::::y         y:::::y P::::P     P:::::Pa::::::::::::a   ss::::::::::s    ss::::::::::sw:::::w         w:::::w         w:::::woo:::::::::::oo r::::rrr:::::::::r    dd::::::::::::::d      G:::::G                ee::::::::::::ee  n:::nn::::::::nn    ee::::::::::::ee  r::::rrr:::::::::r  a::::::::::::a t:::::::::::::::::t     oo:::::::::::oo r::::rrr:::::::::r  !:::!
  P::::PPPPPP:::::P   y:::::y       y:::::y  P::::PPPPPP:::::P aaaaaaaaa:::::ass:::::::::::::s ss:::::::::::::sw:::::w       w:::::::w       w:::::wo:::::::::::::::or:::::::::::::::::r  d::::::::::::::::d      G:::::G               e::::::eeeee:::::een::::::::::::::nn  e::::::eeeee:::::eer:::::::::::::::::r aaaaaaaaa:::::at:::::::::::::::::t    o:::::::::::::::or:::::::::::::::::r !:::!
  P:::::::::::::PP     y:::::y     y:::::y   P:::::::::::::PP           a::::as::::::ssss:::::ss::::::ssss:::::sw:::::w     w:::::::::w     w:::::w o:::::ooooo:::::orr::::::rrrrr::::::rd:::::::ddddd:::::d      G:::::G    GGGGGGGGGGe::::::e     e:::::enn:::::::::::::::ne::::::e     e:::::err::::::rrrrr::::::r         a::::atttttt:::::::tttttt    o:::::ooooo:::::orr::::::rrrrr::::::r!:::!
  P::::PPPPPPPPP        y:::::y   y:::::y    P::::PPPPPPPPP      aaaaaaa:::::a s:::::s  ssssss  s:::::s  ssssss  w:::::w   w:::::w:::::w   w:::::w  o::::o     o::::o r:::::r     r:::::rd::::::d    d:::::d      G:::::G    G::::::::Ge:::::::eeeee::::::e  n:::::nnnn:::::ne:::::::eeeee::::::e r:::::r     r:::::r  aaaaaaa:::::a      t:::::t          o::::o     o::::o r:::::r     r:::::r!:::!
  P::::P                 y:::::y y:::::y     P::::P            aa::::::::::::a   s::::::s         s::::::s        w:::::w w:::::w w:::::w w:::::w   o::::o     o::::o r:::::r     rrrrrrrd:::::d     d:::::d      G:::::G    GGGGG::::Ge:::::::::::::::::e   n::::n    n::::ne:::::::::::::::::e  r:::::r     rrrrrrraa::::::::::::a      t:::::t          o::::o     o::::o r:::::r     rrrrrrr!:::!
  P::::P                  y:::::y:::::y      P::::P           a::::aaaa::::::a      s::::::s         s::::::s      w:::::w:::::w   w:::::w:::::w    o::::o     o::::o r:::::r            d:::::d     d:::::d      G:::::G        G::::Ge::::::eeeeeeeeeee    n::::n    n::::ne::::::eeeeeeeeeee   r:::::r           a::::aaaa::::::a      t:::::t          o::::o     o::::o r:::::r            !!:!!
  P::::P                   y:::::::::y       P::::P          a::::a    a:::::assssss   s:::::s ssssss   s:::::s     w:::::::::w     w:::::::::w     o::::o     o::::o r:::::r            d:::::d     d:::::d       G:::::G       G::::Ge:::::::e             n::::n    n::::ne:::::::e            r:::::r          a::::a    a:::::a      t:::::t    tttttto::::o     o::::o r:::::r             !!! 
PP::::::PP                  y:::::::y      PP::::::PP        a::::a    a:::::as:::::ssss::::::ss:::::ssss::::::s     w:::::::w       w:::::::w      o:::::ooooo:::::o r:::::r            d::::::ddddd::::::dd       G:::::GGGGGGGG::::Ge::::::::e            n::::n    n::::ne::::::::e           r:::::r          a::::a    a:::::a      t::::::tttt:::::to:::::ooooo:::::o r:::::r                 
P::::::::P                   y:::::y       P::::::::P        a:::::aaaa::::::as::::::::::::::s s::::::::::::::s       w:::::w         w:::::w       o:::::::::::::::o r:::::r             d:::::::::::::::::d        GG:::::::::::::::G e::::::::eeeeeeee    n::::n    n::::n e::::::::eeeeeeee   r:::::r          a:::::aaaa::::::a      tt::::::::::::::to:::::::::::::::o r:::::r             !!! 
P::::::::P                  y:::::y        P::::::::P         a::::::::::aa:::as:::::::::::ss   s:::::::::::ss         w:::w           w:::w         oo:::::::::::oo  r:::::r              d:::::::::ddd::::d          GGG::::::GGG:::G  ee:::::::::::::e    n::::n    n::::n  ee:::::::::::::e   r:::::r           a::::::::::aa:::a       tt:::::::::::tt oo:::::::::::oo  r:::::r            !!:!!
PPPPPPPPPP                 y:::::y         PPPPPPPPPP          aaaaaaaaaa  aaaa sssssssssss      sssssssssss            www             www            ooooooooooo    rrrrrrr               ddddddddd   ddddd             GGGGGG   GGGG    eeeeeeeeeeeeee    nnnnnn    nnnnnn    eeeeeeeeeeeeee   rrrrrrr            aaaaaaaaaa  aaaa         ttttttttttt     ooooooooooo    rrrrrrr             !!! 
                          y:::::y                                                                                                                                                                                                                                                                                                                                                                    
                         y:::::y                                                                                                                                                                                                                                                                                                                                                                     
                        y:::::y                                                                                                                                                                                                                                                                                                                                                                      
                       y:::::y                                                                                                                                                                                                                                                                                                                                                                       
                      yyyyyyy                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
"""

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+', '~', '^', '@', '{', '}', '[', ']', '|', '>', '<', '?', ':', ';', '-', '=']

print(welcome)
print(logo)
nr_letters= int(input("How many letters would you like in your password?\n")) 
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))
